# Generated by Django 5.0.2 on 2024-03-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=50)),
                ('inclusion_date', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('apartment_number', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('equipment', models.CharField(max_length=100)),
            ],
        ),
    ]
