# Generated by Django 5.0.2 on 2024-03-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_salesrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cable',
            old_name='name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='cable',
            old_name='length',
            new_name='inclusion_date',
        ),
        migrations.RenameField(
            model_name='cable',
            old_name='article',
            new_name='order_number',
        ),
        migrations.AddField(
            model_name='cable',
            name='apartment_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='company',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='contact_person',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='equipment',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cable',
            name='street',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
